# Generated by Django 4.1.2 on 2022-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='codigo_libro',
            field=models.IntegerField(null=True),
        ),
    ]
