# Generated by Django 4.1.2 on 2022-11-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0002_libro_codigo_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='num_socio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='num_sector',
            field=models.IntegerField(null=True),
        ),
    ]
